# HomeSystem OCR 服务独立部署
# PaddleOCR 文档识别服务
# 适合部署在 GPU 服务器上，为其他服务提供 OCR 能力

version: '3.8'

services:
  # OCR 服务 - PaddleOCR文档识别
  ocr-service:
    image: ghcr.io/yangtao121/remote-app-ocr:main
    container_name: homesystem-ocr
    restart: unless-stopped
    # 如果有 NVIDIA GPU，请取消注释下面一行
    # runtime: nvidia
    ports:
      - "5001:5001"
    environment:
      # OCR 服务配置
      HOST: 0.0.0.0
      OCR_SERVICE_PORT: 5001
      DEBUG: false
      LOG_LEVEL: INFO
      LOG_FILE: ocr_service.log
      
      # 请求限制配置
      MAX_CONTENT_LENGTH: 100  # MB
      REQUEST_TIMEOUT: 300     # 秒
      
      # OCR 处理设置
      OCR_MAX_PAGES: 25
      OCR_TEMP_DIR: /tmp/ocr_service
      OCR_RESULTS_DIR: /tmp/ocr_results
      
      # PaddleOCR 配置
      PADDLEOCR_USE_ANGLE_CLS: true
      PADDLEOCR_USE_GPU: false    # ⚠️ 如有 GPU 设置为 true
      PADDLEOCR_LANG: ch          # 支持中文
      PADDLEOCR_HOME: /app/.paddleocr
      HUB_HOME: /app/.paddlehub
      
      # 如果有 NVIDIA GPU，请取消注释下面一行
      # NVIDIA_VISIBLE_DEVICES: all
      
      # 可选：API Key 认证
      API_KEY:  # 留空表示不启用认证
      
      # 系统配置
      TZ: Asia/Shanghai
      PYTHONUNBUFFERED: 1
      PYTHONIOENCODING: utf-8
    volumes:
      # PaddleOCR 模型缓存，避免重复下载大模型文件
      - ocr_models:/app/.paddleocr
      - ocr_hub:/app/.paddlehub
      
      # OCR 结果输出目录
      - ocr_results:/tmp/ocr_results
      
      # 临时文件目录
      - ocr_temp:/tmp/ocr_service
      
      # 日志目录
      - ocr_logs:/app/logs
      
      # 可选：自定义配置目录
      # - ./config:/app/config:ro
    
    # 资源限制配置（可根据服务器配置调整）
    deploy:
      resources:
        limits:
          memory: 2G      # 最大内存使用
          cpus: '2.0'     # 最大CPU使用
        reservations:
          memory: 512M    # 保留内存
          cpus: '0.5'     # 保留CPU
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # 启动时间较长，给足够的启动时间
    
    networks:
      - ocr-network

# 数据卷定义
volumes:
  ocr_models:
    name: homesystem-ocr-models
  ocr_hub:
    name: homesystem-ocr-hub
  ocr_results:
    name: homesystem-ocr-results
  ocr_temp:
    name: homesystem-ocr-temp
  ocr_logs:
    name: homesystem-ocr-logs

# 网络定义
networks:
  ocr-network:
    driver: bridge
    name: homesystem-ocr-network

# 部署说明：
# 
# GPU 服务器部署步骤：
# 1. 安装 nvidia-docker: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html
# 2. 取消注释 runtime: nvidia 和 NVIDIA_VISIBLE_DEVICES
# 3. 设置 PADDLEOCR_USE_GPU: true
# 4. 启动服务：docker compose -f docker-compose.ocr.yml up -d
# 
# CPU 服务器部署步骤：
# 1. 保持默认配置（GPU相关设置为false）
# 2. 启动服务：docker compose -f docker-compose.ocr.yml up -d
# 
# 服务地址：
# - OCR API: http://服务器IP:5001
# - 健康检查: http://服务器IP:5001/api/health
# - API文档: http://服务器IP:5001/docs (如果启用)
# 
# 性能调优：
# - GPU服务器：建议内存4GB+，启用GPU加速
# - CPU服务器：建议内存2GB+，CPU 2核+
# - 网络：确保其他服务能访问 5001 端口
# 
# 使用方式：
# 其他服务通过 REMOTE_OCR_ENDPOINT=http://OCR服务器IP:5001 连接